language: c
script:
  - asdf plugin-test graalvm https://github.com/vic/asdf-graalvm.git "polyglot --version"
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
